### ISSUE TITLE
Suggestion: Add "general_log" to repository description

### ISSUE THREAD

**Issue by jonaseberle** [ChromaticHQ/ddev-dblog#3]
Hi, thanks for making this a proper add-on. It works great.

I was expecting to find this add-on by looking for "general_log" in `ddev get --list --all`. I was expecting that because the setting has that name in MySQL and that's all I could think of.

In PostgreSQL it is "log_statement=all" for that matter ;)

**Comment by apotek** [comment]
I added `general_log` to the one line description, as you suggested. I'll leave out any postgres stuff until postgres support is (if) ever implemented.
